stages:
- name: test1
  steps:
  - runScriptConfig:
      image: ubuntu
      shellScript: |-
        apt-get update
        apt-get install -y nodejs npm
        npm install -g vamp-cli-ee
        sleep 10
        which vamp
  - runScriptConfig:
      image: magneticio/vamp-cli-ee:0.8.0
      shellScript: |-
        vamp --version
        
