timeout: 60
notification: {}

# example
stages:
  - name: Build something
    # Conditions for stages
    when:
      branch: master
      event: [ push, pull_request ]
    # Multiple steps run concurrently
    steps:
    - runScriptConfig:
        image: alpine
        shellScript: apk add --update nodejs && npm install -g vamp-cli-ee
      env:
        FIRST_KEY: VALUE
        SECOND_KEY: VALUE2
      # Set environment variables from project secrets
    - runScriptConfig:
        image: alpine
        shellScript: date -R
      # Conditions for steps
      when:
        branch: [ master, dev ]
        event: push
