stages:
- name: test1
  steps:
  - runScriptConfig:
      image: ubuntu
      shellScript: |-
        apt-get update
        apt-get install -y nodejs npm
        npm install -g vamp-cli-ee
        vamp --version
#         docker-php-ext-install zip
#         curl --silent --show-error https://getcomposer.org/installer | php
#         ./composer.phar install -n --prefer-dist
#         touch storage/testing.sqlite storage/database.sqlite
#         cp .env.testing .env
#         php artisan migrate
#         php artisan migrate --env=testing --database=sqlite_testing --force
#         ./vendor/bin/codecept build
#         ./vendor/bin/codecept run


# # example
# stages:
#   - name: Build something
#     # Conditions for stages
#     when:
#       branch: master
#       event: [ push, pull_request ]
#     # Multiple steps run concurrently
#     steps:
#     - runScriptConfig:
#         image: alpine
#         shellScript: apk add --update nodejs && npm install -g vamp-cli-ee
#       env:
#         FIRST_KEY: VALUE
#         SECOND_KEY: VALUE2
#       # Set environment variables from project secrets
#     - runScriptConfig:
#         image: alpine
#         shellScript: date -R
#       # Conditions for steps
#       when:
#         branch: [ master, dev ]
#         event: push
