stages:
- name: test1
  steps:
  - runScriptConfig:
      image: ubuntu
      isShell: true
      shellScript: |-
        apt-get update
        apt-get install -y nodejs npm
        npm install -g vamp-cli-ee
        sleep 10
        which vamp
        export VAMP_HOST=${VAMP_HOST}
        export VAMP_TOKEN=${VAMP_TOKEN}
        export VAMP_NAMESPACE=${VAMP_NAMESPACE}
        echo -V  |  vamp list deployments
        
